package fxproject.backend.tableHandlers;

public enum ColumnNames {
    ID_COLUMN,
    OWNER_ID_COLUMN,
    NAME_COLUMN,
    COORDINATES_X_COLUMN,
    COORDINATES_Y_COLUMN,
    CREATION_DATE_COLUMN,
    NUMBER_OF_PARTICIPANTS_COLUMN,
    GENRE_COLUMN,
    PERSON_NAME_COLUMN,
    PERSON_HEIGHT_COLUMN,
    PERSON_NATIONALITY_COLUMN,
    LOCATION_X_COORDINATE,
    LOCATION_Y_COORDINATE,
    LOCATION_Z_COORDINATE
}
